import Blogs from "@/components/Blogs/Blogs";
import MainLayout from "@/layouts/MainLayout";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Blog Site App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<MainLayout>
					<Blogs />
				</MainLayout>
			</main>
		</>
	);
}
